# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    ide: 'phpstorm://open?url=file://%%f&line=%%l'
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    messenger:
        reset_on_message: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
